{% set name = "datasketch" %}
{% set version = "1.5.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ekzhu/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 909c81223834778b85b101cc2a764d0f5f626dc75335511c07419ea103fc8868

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation --ignore-installed -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - numpy >1.11
    - scipy >=1.0.0
  run_constrained:
    - cassandra-driver >=3.20
    - redis >=2.10.0

test:
  imports:
    - datasketch
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://ekzhu.com/datasketch
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Probabilistic data structures for processing and searching very large datasets
  description: |
    datasketch gives you probabilistic data structures 
    that can process and search very large amount of data super fast, with little loss of accuracy.
  doc_url: https://ekzhu.com/datasketch/
  dev_url: https://github.com/ekzhu/datasketch
